import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import grid from '../public/grid.svg'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  console.log(grid)
  return (
    <html lang="en" className="relative h-[200vh]">
      <body className={inter.className}>
        {children}
        {/* <Image src={grid} alt="grid" className='absolute top-0 left-0 w-full h-fit object-fill' /> */}
      </body>
    </html>
  )
}
