import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className="bg-black text-white">
      <body className={inter.className}>
        <div id='pattern'></div>
        <div id='noise'></div>
        {children}
      </body>
    </html>
  )
}
